const copy = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dictum, velit sed tristique cursus, lectus magna condimentum massa, et molestie sem tortor ut magna. Aliquam id enim quis nisl ultrices laoreet. Mauris pretium augue quis posuere venenatis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi sit amet diam sed enim iaculis consequat. Ut fringilla, magna placerat hendrerit lobortis, est nisl varius dui, id eleifend ex nunc nec felis. Proin condimentum eleifend nunc porttitor imperdiet. Cras ut sem nec odio maximus condimentum id at tortor. Ut sed facilisis sem. Donec et congue metus.

Maecenas commodo laoreet libero a malesuada. Donec vulputate blandit nulla ac fermentum. Ut viverra, mi sed bibendum ultricies, ligula est condimentum sem, fermentum vehicula ante urna quis sapien. Fusce porta dignissim aliquam. Integer vel mattis dolor, in facilisis enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec volutpat enim id ante vulputate, in molestie arcu facilisis. Maecenas ornare consectetur eros et tincidunt. In quis massa vel tortor scelerisque bibendum.

Proin aliquam dolor eget mi congue, vitae tincidunt nisi laoreet. Quisque pretium nisl quis luctus euismod. Sed risus tortor, cursus eget nisi vitae, tristique vulputate ante. Morbi ullamcorper mi risus, a facilisis massa elementum sed. Ut porta libero vel ultricies pellentesque. Nulla facilisi. Suspendisse placerat mi nec sem vehicula elementum. Praesent tristique orci nec ipsum maximus fermentum. Integer sagittis, nulla id consectetur rutrum, ligula erat feugiat sapien, id congue ex elit ut mi. Vestibulum quis massa tellus. Quisque viverra, ligula ac ultricies eleifend, tortor libero ullamcorper libero, sit amet facilisis nisl nulla sed nibh. Nulla facilisi. Praesent in erat at est venenatis posuere in at metus. Praesent commodo nec lorem id consequat.

In dictum tellus nec luctus tempus. Phasellus posuere ipsum interdum, fermentum tortor ut, hendrerit lacus. Curabitur cursus, sem eu eleifend pharetra, arcu ipsum vehicula arcu, in vehicula velit eros in nulla. In tempor magna in est sagittis rutrum. Sed fermentum fringilla venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam erat volutpat. Donec mattis elit eros, sit amet tristique sapien tristique nec. Nam vel odio at ligula ullamcorper dapibus. Nullam elementum arcu velit, at commodo dui viverra id. Maecenas tincidunt congue finibus. Maecenas ornare sollicitudin volutpat. Suspendisse pellentesque ullamcorper tempor. Ut vehicula magna odio, in malesuada orci pellentesque eget. Curabitur elit lectus, tempor nec metus accumsan, vulputate dapibus leo.

Morbi ut finibus felis, ac posuere metus. Quisque gravida, nisi sit amet commodo fringilla, dui risus dapibus libero, et gravida turpis purus rutrum odio. Aliquam erat volutpat. Maecenas sed sem non nisi consequat fringilla. Nullam quis pulvinar mauris. Nulla facilisi. Ut sodales aliquam condimentum. Sed vel libero ornare, accumsan nulla id, volutpat tortor. Curabitur fermentum lectus at bibendum cursus. Pellentesque lacinia leo non risus viverra, ut ornare tellus iaculis. Nam laoreet sapien at odio imperdiet, feugiat commodo nunc dapibus. Quisque auctor dapibus ex id elementum. Aenean eget eleifend metus, et tristique risus.`

export const LoginBg = () => {
  return (
    <div className="-z-10 t fixed inset-0 mx-auto flex h-full max-w-4xl flex-col items-center justify-center overflow-hidden bg-[linear-gradient(to_bottom,rgba(255,255,255,0.25)_0%,rgba(255,255,255,0)_50%,rgba(255,255,255,0.25)_100%)] bg-clip-text font-mono text-transparent text-xs">
      {copy}
      {copy}
    </div>
  )
}
